openapi: 3.1.0
info:
  title: Echo Template API
  description: |
    基于 Echo 框架的模板项目 API 文档

    ## 响应格式说明
    所有API响应都使用统一的格式，HTTP状态码固定为200，通过 `code` 字段区分成功和失败：
    - `code = 0`: 请求成功
    - `code != 0`: 请求失败，具体错误码请参考错误码表

    ## 认证说明
    需要认证的接口使用 Bearer Token 认证，在请求头中添加：
    ```
    Authorization: Bearer <access_token>
    ```
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8000
    description: 开发环境
  - url: https://api.example.com
    description: 生产环境
tags:
  - name: 认证管理
    description: 用户注册、登录、令牌管理等认证相关接口
  - name: 当前用户
    description: 用户信息查询和管理接口
x-tagGroups:
  - name: 核心功能
    tags:
      - 认证管理
      - 当前用户
paths:
  /api/v1/auth/register:
    $ref: paths/api_v1_auth_register.yaml
  /api/v1/auth/login:
    $ref: paths/api_v1_auth_login.yaml
  /api/v1/auth/refresh:
    $ref: paths/api_v1_auth_refresh.yaml
  /api/v1/auth/logout:
    $ref: paths/api_v1_auth_logout.yaml
  /api/v1/me:
    $ref: paths/api_v1_me.yaml
  /api/v1/me/username:
    $ref: paths/api_v1_me_username.yaml
  /api/v1/me/email:
    $ref: paths/api_v1_me_email.yaml
  /api/v1/me/change-password:
    $ref: paths/api_v1_me_change-password.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'JWT访问令牌，格式: Bearer `<token>`'
  schemas:
    # 认证相关
    RegisterInput:
      $ref: components/schemas/RegisterInput.yaml
    LoginInput:
      $ref: components/schemas/LoginInput.yaml
    RefreshTokenInput:
      $ref: components/schemas/RefreshTokenInput.yaml
    AuthOutput:
      $ref: components/schemas/AuthOutput.yaml
    # 用户相关
    UserInfo:
      $ref: components/schemas/UserInfo.yaml
    UpdateUsernameInput:
      $ref: components/schemas/UpdateUsernameInput.yaml
    UpdateEmailInput:
      $ref: components/schemas/UpdateEmailInput.yaml
    ChangePasswordInput:
      $ref: components/schemas/ChangePasswordInput.yaml
    # 统一响应模式 - 基础组件
    BaseResponse:
      $ref: components/schemas/BaseResponse.yaml
    SuccessResponse:
      $ref: components/schemas/SuccessResponse.yaml
    ErrorResponse:
      $ref: components/schemas/ErrorResponse.yaml
    ApiResponse:
      $ref: components/schemas/ApiResponse.yaml
    # 统一响应模式 - 具体业务场景
    AuthSuccessResponse:
      $ref: components/schemas/AuthSuccessResponse.yaml
    UserSuccessResponse:
      $ref: components/schemas/UserSuccessResponse.yaml
    SimpleSuccessResponse:
      $ref: components/schemas/SimpleSuccessResponse.yaml
    AuthApiResponse:
      $ref: components/schemas/AuthApiResponse.yaml
    UserApiResponse:
      $ref: components/schemas/UserApiResponse.yaml
    SimpleApiResponse:
      $ref: components/schemas/SimpleApiResponse.yaml
